framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    router:
        default_uri: '%env(DEFAULT_URI)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
