admin_seo:
    resource: ../src/Controller/SeoAdminController.php
    type: attribute

controllers:
    resource: ../src/Controller/DemoController.php
    type: attribute
    prefix: /{_locale}
    trailing_slash_on_root: false
    requirements:
        _locale: en|es|fr
    defaults:
        _locale: en

nowo_seo_kit:
    resource: .
    type: nowo_seo_kit
